/*
* Icon Library Configuration
- 此檔案負責註冊所有需要使用的 FontAwesome 圖標
- 只有在此處註冊的圖標才能在 Icon Component 中使用
*/

import { library, IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faPersonRunning,
  faTrophy,
  faTv,
  faWaveSquare,
  faArrowRight,
  faArrowsSpin,
  faBars,
  faBookOpen,
  faCamera,
  faChalkboardUser,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleNotch,
  faCircleXmark,
  faCode,
  faCodeBranch,
  faCog,
  faCompass,
  faCopy,
  faCrown,
  faDatabase,
  faDiagramProject,
  faDownload,
  faDungeon,
  faEdit,
  faEllipsisV,
  faEnvelope,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faFileLines,
  faFilm,
  faFire,
  faFilter,
  faFlask,
  faGear,
  faGhost,
  faGlobe,
  faHourglassHalf,
  faHome,
  faInfoCircle,
  faLayerGroup,
  faLightbulb,
  faLink,
  faLocationCrosshairs,
  faLock,
  faMagnifyingGlass,
  faMinus,
  faMoon,
  faPalette,
  faPause,
  faPencil,
  faPenToSquare,
  faPlay,
  faPlus,
  faQuestionCircle,
  faRedo,
  faRightLeft,
  faRotate,
  faRotateRight,
  faSave,
  faScrewdriverWrench,
  faSearch,
  faShuffle,
  faSignal,
  faSignOutAlt,
  faSitemap,
  faSliders,
  faSpinner,
  faStar,
  faStepBackward,
  faStepForward,
  faStopwatch,
  faSun,
  faSync,
  faTable,
  faTableCells,
  faTerminal,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faUserCircle,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircle as farCircle,
  faCheckCircle as farCheckCircle,
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons';

/**
 * 1. 集中管理映射表
 * 這樣做的好處是：名稱與對象一一對應，且 VS Code 能自動推斷類型
 */
export const iconMap = {
  "arrow-left": faArrowLeft,
  "arrow-right": faArrowRight,
  "arrows-spin": faArrowsSpin,
  "bars": faBars,
  "book-open": faBookOpen,
  "camera": faCamera,
  "chalkboard-user": faChalkboardUser,
  "chart-bar": faChartBar,
  "chart-line": faChartLine,
  "check": faCheck,
  "check-circle": farCheckCircle,
  "chevron-down": faChevronDown,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "chevron-up": faChevronUp,
  "circle": farCircle,
  "circle-notch": faCircleNotch,
  "circle-xmark": faCircleXmark,
  "code": faCode,
  "code-branch": faCodeBranch,
  "cog": faCog,
  "compass": faCompass,
  "copy": faCopy,
  "crown": faCrown,
  "database": faDatabase,
  "diagram-project": faDiagramProject,
  "download": faDownload,
  "dungeon": faDungeon,
  "edit": faEdit,
  "ellipsis-v": faEllipsisV,
  "envelope": faEnvelope,
  "exclamation-circle": faExclamationCircle,
  "eye": faEye,
  "eye-off": faEyeSlash,
  "eye-slash": faEyeSlash,
  "file-lines": faFileLines,
  "film": faFilm,
  "fire": faFire,
  "filter": faFilter,
  "flask": faFlask,
  "gear": faGear,
  "ghost": faGhost,
  "globe": faGlobe,
  "hourglass-half": faHourglassHalf,
  "home": faHome,
  "info-circle": faInfoCircle,
  "layer-group": faLayerGroup,
  "link": faLink,
  "lightbulb": faLightbulb,
  "location-crosshairs": faLocationCrosshairs,
  "lock": faLock,
  "magnifying-glass": faMagnifyingGlass,
  "minus": faMinus,
  "moon": faMoon,
  "palette": faPalette,
  "person-running": faPersonRunning,
  "wave-square": faWaveSquare,
  "pause": faPause,
  "pencil": faPencil,
  "pen-to-square": faPenToSquare,
  "play": faPlay,
  "plus": faPlus,
  "question-circle": faQuestionCircle,
  "redo": faRedo,
  "right-left": faRightLeft,
  "rotate": faRotate,
  "rotate-right": faRotateRight,
  "save": faSave,
  "screwdriver-wrench": faScrewdriverWrench,
  "search": faSearch,
  "shuffle": faShuffle,
  "signal": faSignal,
  "sign-out-alt": faSignOutAlt,
  "sitemap": faSitemap,
  "sliders": faSliders,
  "spinner": faSpinner,
  "star": faStar,
  "star-outline": farStar,
  "step-backward": faStepBackward,
  "step-forward": faStepForward,
  "stopwatch": faStopwatch,
  "sun": faSun,
  "sync": faSync,
  "table": faTable,
  "table-cells": faTableCells,
  "terminal": faTerminal,
  "times": faTimes,
  "trash": faTrash,
  "trophy": faTrophy,
  "tv": faTv,
  "upload": faUpload,
  "user": faUser,
  "user-circle": faUserCircle,
} as const;

/**
 * 2. 自動執行註冊
 * Object.values 會抓出所有的 IconDefinition
 */
library.add(...(Object.values(iconMap) as IconDefinition[]));

/**
 * 3. 自動生成類型
 * 這行代碼會自動提取 iconMap 的所有 Key
 * 你以後不需要手動寫 | 'user' | 'cog' ...
 */
export type IconName = keyof typeof iconMap;
