"""init core tables

Revision ID: 102313367aee
Revises: 
Create Date: 2026-03-04 21:00:02.669489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102313367aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorials',
    sa.Column('tutorial_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_zh', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('xp_teaching', sa.Integer(), nullable=False),
    sa.Column('xp_practice_base', sa.Integer(), nullable=False),
    sa.Column('xp_perfect_bonus', sa.Integer(), nullable=False),
    sa.Column('graph_layer', sa.Integer(), nullable=False),
    sa.Column('graph_branch', sa.String(length=50), nullable=False),
    sa.Column('graph_horizontal_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tutorial_id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.create_index('ix_tutorials_category_order', ['category_id', 'display_order'], unique=False)
        batch_op.create_index('ix_tutorials_published', ['is_published'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_identities',
    sa.Column('identity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('local', 'google', 'github', name='providertype'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_identity_provider')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index('ix_user_identities_user_id', ['user_id'], unique=False)

    op.create_table('user_tutorial_progress',
    sa.Column('progress_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('teaching_completed', sa.Boolean(), nullable=True),
    sa.Column('teaching_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('best_correct_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('practice_passed', sa.Boolean(), nullable=True),
    sa.Column('practice_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('teaching_in_progress', 'teaching_done', 'practicing', 'completed', name='tutorialstatus'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name='uq_user_tutorial_progress')
    )
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.create_index('ix_utp_status', ['status'], unique=False)
        batch_op.create_index('ix_utp_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_utp_user_id')
        batch_op.drop_index('ix_utp_status')

    op.drop_table('user_tutorial_progress')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_user_identities_user_id')

    op.drop_table('user_identities')
    op.drop_table('users')
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_index('ix_tutorials_published')
        batch_op.drop_index('ix_tutorials_category_order')

    op.drop_table('tutorials')
    # ### end Alembic commands ###
