""""update_ExploreHistory_replay_fields"

Revision ID: 17e147eb2a57
Revises: 929d103c7ec1
Create Date: 2026-05-10 04:30:49.445198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e147eb2a57'
down_revision = '929d103c7ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_trace', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('raw_index_map', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('call_graph', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cfg_graph', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('stdout_events', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('top3_candidates', sa.JSON(), nullable=True))
        batch_op.drop_column('space_complexity')
        batch_op.drop_column('llm_summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('space_complexity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('top3_candidates')
        batch_op.drop_column('stdout_events')
        batch_op.drop_column('cfg_graph')
        batch_op.drop_column('call_graph')
        batch_op.drop_column('raw_index_map')
        batch_op.drop_column('raw_trace')
        batch_op.drop_column('ai_feedback')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
