""""add_visual_to_questions"

Revision ID: 21a559180677
Revises: c3a1f9d2e847
Create Date: 2026-05-23 04:01:06.605783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a559180677'
down_revision = 'c3a1f9d2e847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_alt', sa.Text(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_type', sa.String(length=20), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('visual_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('visual_data')
        batch_op.drop_column('visual_type')

    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.drop_column('visual_alt')

    # ### end Alembic commands ###
