""""refactor_user_schema_add_username_and_enum_types"

Revision ID: 3fd4bcecf200
Revises: 8790b2fa3830
Create Date: 2026-03-14 15:54:03.088916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd4bcecf200'
down_revision = '8790b2fa3830'
branch_labels = None
depends_on = None


def upgrade():
    # Create enum types first
    theme_enum = sa.Enum('light', 'dark', 'system', name='theme')
    language_enum = sa.Enum('en', 'zh_TW', name='language')
    theme_enum.create(op.get_bind(), checkfirst=True)
    language_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=15), nullable=False))
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('light', 'dark', 'system', name='theme'),
               existing_nullable=True,
               postgresql_using='theme::theme')
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('en', 'zh_TW', name='language'),
               existing_nullable=True,
               postgresql_using='language::language')
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_xp_achievement'), postgresql_where="((source_type)::text = 'achievement_unlock'::text)")
        batch_op.drop_index(batch_op.f('ux_xp_practice_pass'), postgresql_where="((source_type)::text = 'practice_pass'::text)")
        batch_op.drop_index(batch_op.f('ux_xp_practice_perfect'), postgresql_where="((source_type)::text = 'practice_perfect'::text)")
        batch_op.drop_index(batch_op.f('ux_xp_teaching'), postgresql_where="((source_type)::text = 'teaching_complete'::text)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_xp_teaching'), ['user_id', 'source_id'], unique=True, postgresql_where="((source_type)::text = 'teaching_complete'::text)")
        batch_op.create_index(batch_op.f('ux_xp_practice_perfect'), ['user_id', 'source_id'], unique=True, postgresql_where="((source_type)::text = 'practice_perfect'::text)")
        batch_op.create_index(batch_op.f('ux_xp_practice_pass'), ['user_id', 'source_id'], unique=True, postgresql_where="((source_type)::text = 'practice_pass'::text)")
        batch_op.create_index(batch_op.f('ux_xp_achievement'), ['user_id', 'source_id'], unique=True, postgresql_where="((source_type)::text = 'achievement_unlock'::text)")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('language',
               existing_type=sa.Enum('en', 'zh_TW', name='language'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('theme',
               existing_type=sa.Enum('light', 'dark', 'system', name='theme'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
