""""msg=init_all_schema"

Revision ID: 46d8f6557002
Revises: 
Create Date: 2026-03-09 03:40:16.377731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d8f6557002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('achievement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('achievement_id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('achievement_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_achievement_definitions_active', ['is_active'], unique=False)
        batch_op.create_index('ix_achievement_definitions_category', ['category'], unique=False)
        batch_op.create_index('ix_achievement_definitions_slug', ['slug'], unique=False)

    op.create_table('algorithm_categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color_theme', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('email_verifications',
    sa.Column('verification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('registration', 'password_reset', name='verificationpurpose'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('verification_id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_email_verifications_email', ['email'], unique=False)
        batch_op.create_index('ix_email_verifications_email_created', ['email', 'created_at'], unique=False)
        batch_op.create_index('ix_email_verifications_expires_at', ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('skill_rating', sa.Float(), nullable=False),
    sa.Column('skill_tier', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('achievement_translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definitions.achievement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_id', 'language_code', name='uq_achievement_translation')
    )
    with op.batch_alter_table('achievement_translations', schema=None) as batch_op:
        batch_op.create_index('ix_achievement_translations_achievement_id', ['achievement_id'], unique=False)

    op.create_table('algorithm_category_translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['algorithm_categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_code', name='uq_category_translation')
    )
    with op.batch_alter_table('algorithm_category_translations', schema=None) as batch_op:
        batch_op.create_index('ix_algo_cat_trans_category_id', ['category_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_audit_logs_event_timestamp', ['event_timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_audit_logs_table_record', ['table_name', 'record_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('explore_histories',
    sa.Column('explore_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('detected_algorithm', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('time_complexity', sa.String(length=50), nullable=True),
    sa.Column('space_complexity', sa.String(length=50), nullable=True),
    sa.Column('analysis_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explore_id')
    )
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.create_index('ix_explore_histories_detected_algorithm', ['detected_algorithm'], unique=False)
        batch_op.create_index('ix_explore_histories_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_explore_histories_user_id', ['user_id'], unique=False)

    op.create_table('tutorials',
    sa.Column('tutorial_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('time_complexity', sa.String(length=50), nullable=True),
    sa.Column('space_complexity', sa.String(length=50), nullable=True),
    sa.Column('implementation_key', sa.String(length=100), nullable=True),
    sa.Column('practice_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('xp_teaching', sa.Integer(), nullable=False),
    sa.Column('xp_practice_base', sa.Integer(), nullable=False),
    sa.Column('xp_perfect_bonus', sa.Integer(), nullable=False),
    sa.Column('graph_layer', sa.Integer(), nullable=False),
    sa.Column('graph_branch', sa.String(length=50), nullable=False),
    sa.Column('graph_horizontal_index', sa.Integer(), nullable=False),
    sa.Column('path_type', sa.String(length=20), nullable=False),
    sa.Column('branch_label', sa.String(length=50), nullable=True),
    sa.Column('path_color_theme', sa.String(length=20), nullable=True),
    sa.Column('portal_target_category_id', sa.BigInteger(), nullable=True),
    sa.Column('prerequisite_type', sa.String(length=10), nullable=False),
    sa.Column('homepage_image', sa.String(length=200), nullable=True),
    sa.Column('homepage_translation_key', sa.String(length=100), nullable=True),
    sa.Column('show_on_homepage', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['algorithm_categories.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portal_target_category_id'], ['algorithm_categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tutorial_id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.create_index('ix_tutorials_category_graph', ['category_id', 'graph_layer', 'graph_branch'], unique=False)
        batch_op.create_index('ix_tutorials_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_tutorials_category_order', ['category_id', 'display_order'], unique=False)
        batch_op.create_index('ix_tutorials_published', ['is_published'], unique=False)
        batch_op.create_index('ix_tutorials_slug', ['slug'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definitions.achievement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index('ix_user_achievements_unlocked_at', ['unlocked_at'], unique=False)
        batch_op.create_index('ix_user_achievements_user_id', ['user_id'], unique=False)

    op.create_table('user_identities',
    sa.Column('identity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('local', 'google', 'github', name='providertype'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_identity_provider')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index('ix_user_identities_user_id', ['user_id'], unique=False)

    op.create_table('user_login_streaks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'login_date', name='uq_user_login_date')
    )
    with op.batch_alter_table('user_login_streaks', schema=None) as batch_op:
        batch_op.create_index('ix_user_login_streaks_date', ['login_date'], unique=False)
        batch_op.create_index('ix_user_login_streaks_user_id', ['user_id'], unique=False)

    op.create_table('user_tokens',
    sa.Column('token_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_user_tokens_hash', ['token_hash'], unique=False)
        batch_op.create_index('ix_user_tokens_user_active', ['user_id', 'is_revoked', 'expires_at'], unique=False)
        batch_op.create_index('ix_user_tokens_user_id', ['user_id'], unique=False)

    op.create_table('xp_events',
    sa.Column('xp_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('xp_event_id')
    )
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index('ix_xp_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_xp_events_source_type', ['source_type'], unique=False)
        batch_op.create_index('ix_xp_events_user_id', ['user_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_learning_sessions_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_learning_sessions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_learning_sessions_user_tutorial', ['user_id', 'tutorial_id'], unique=False)

    op.create_table('practice_attempts',
    sa.Column('attempt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('user_rating_before', sa.Float(), nullable=False),
    sa.Column('user_rating_after', sa.Float(), nullable=False),
    sa.Column('rating_delta', sa.Float(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_practice_attempts_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('ix_practice_attempts_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_practice_attempts_user_tutorial', ['user_id', 'tutorial_id'], unique=False)

    op.create_table('question_groups',
    sa.Column('group_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    with op.batch_alter_table('question_groups', schema=None) as batch_op:
        batch_op.create_index('ix_question_groups_tutorial_id', ['tutorial_id'], unique=False)
        batch_op.create_index('ix_question_groups_tutorial_order', ['tutorial_id', 'display_order'], unique=False)

    op.create_table('tutorial_prerequisites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('prerequisite_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutorial_id', 'prerequisite_id', name='uq_tutorial_prerequisite')
    )
    with op.batch_alter_table('tutorial_prerequisites', schema=None) as batch_op:
        batch_op.create_index('ix_tutorial_prerequisites_prereq_id', ['prerequisite_id'], unique=False)
        batch_op.create_index('ix_tutorial_prerequisites_tutorial_id', ['tutorial_id'], unique=False)

    op.create_table('tutorial_suggestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('suggested_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['suggested_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutorial_id', 'suggested_id', name='uq_tutorial_suggestion')
    )
    with op.batch_alter_table('tutorial_suggestions', schema=None) as batch_op:
        batch_op.create_index('ix_tutorial_suggestions_tutorial_id', ['tutorial_id'], unique=False)

    op.create_table('tutorial_translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutorial_id', 'language_code', name='uq_tutorial_translation')
    )
    with op.batch_alter_table('tutorial_translations', schema=None) as batch_op:
        batch_op.create_index('ix_tutorial_translations_tutorial_id', ['tutorial_id'], unique=False)

    op.create_table('question_group_translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'language_code', name='uq_question_group_translation')
    )
    with op.batch_alter_table('question_group_translations', schema=None) as batch_op:
        batch_op.create_index('ix_qgt_group_id', ['group_id'], unique=False)

    op.create_table('questions',
    sa.Column('question_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('difficulty_rating', sa.Float(), nullable=False),
    sa.Column('times_answered', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_difficulty', ['difficulty_rating'], unique=False)
        batch_op.create_index('ix_questions_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_questions_tutorial_id', ['tutorial_id'], unique=False)
        batch_op.create_index('ix_questions_tutorial_order', ['tutorial_id', 'display_order'], unique=False)
        batch_op.create_index('ix_questions_type', ['question_type'], unique=False)

    op.create_table('user_tutorial_progress',
    sa.Column('progress_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tutorial_id', sa.BigInteger(), nullable=False),
    sa.Column('teaching_completed', sa.Boolean(), nullable=True),
    sa.Column('teaching_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('best_correct_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('best_attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('best_time_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('practice_passed', sa.Boolean(), nullable=True),
    sa.Column('practice_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('teaching_in_progress', 'teaching_done', 'practicing', 'completed', name='tutorialstatus'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_attempt_id'], ['practice_attempts.attempt_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.tutorial_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name='uq_user_tutorial_progress')
    )
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.create_index('ix_utp_last_accessed', ['last_accessed_at'], unique=False)
        batch_op.create_index('ix_utp_status', ['status'], unique=False)
        batch_op.create_index('ix_utp_user_id', ['user_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('answer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('question_difficulty_rating', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_attempts.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_answers_attempt_id', ['attempt_id'], unique=False)

    op.create_table('question_translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'language_code', name='uq_question_translation')
    )
    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.create_index('ix_question_translations_question_id', ['question_id'], unique=False)

    # XP 防重複發放 Partial Unique Index（SQLAlchemy 無法自動生成，手動建立）
    op.execute("""
        CREATE UNIQUE INDEX ux_xp_teaching
          ON xp_events (user_id, source_id)
          WHERE source_type = 'teaching_complete'
    """)
    op.execute("""
        CREATE UNIQUE INDEX ux_xp_practice_pass
          ON xp_events (user_id, source_id)
          WHERE source_type = 'practice_pass'
    """)
    op.execute("""
        CREATE UNIQUE INDEX ux_xp_practice_perfect
          ON xp_events (user_id, source_id)
          WHERE source_type = 'practice_perfect'
    """)
    op.execute("""
        CREATE UNIQUE INDEX ux_xp_achievement
          ON xp_events (user_id, source_id)
          WHERE source_type = 'achievement_unlock'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.drop_index('ix_question_translations_question_id')

    op.drop_table('question_translations')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_answers_attempt_id')

    op.drop_table('attempt_answers')
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_utp_user_id')
        batch_op.drop_index('ix_utp_status')
        batch_op.drop_index('ix_utp_last_accessed')

    op.drop_table('user_tutorial_progress')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_type')
        batch_op.drop_index('ix_questions_tutorial_order')
        batch_op.drop_index('ix_questions_tutorial_id')
        batch_op.drop_index('ix_questions_group_id')
        batch_op.drop_index('ix_questions_difficulty')

    op.drop_table('questions')
    with op.batch_alter_table('question_group_translations', schema=None) as batch_op:
        batch_op.drop_index('ix_qgt_group_id')

    op.drop_table('question_group_translations')
    with op.batch_alter_table('tutorial_translations', schema=None) as batch_op:
        batch_op.drop_index('ix_tutorial_translations_tutorial_id')

    op.drop_table('tutorial_translations')
    with op.batch_alter_table('tutorial_suggestions', schema=None) as batch_op:
        batch_op.drop_index('ix_tutorial_suggestions_tutorial_id')

    op.drop_table('tutorial_suggestions')
    with op.batch_alter_table('tutorial_prerequisites', schema=None) as batch_op:
        batch_op.drop_index('ix_tutorial_prerequisites_tutorial_id')
        batch_op.drop_index('ix_tutorial_prerequisites_prereq_id')

    op.drop_table('tutorial_prerequisites')
    with op.batch_alter_table('question_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_question_groups_tutorial_order')
        batch_op.drop_index('ix_question_groups_tutorial_id')

    op.drop_table('question_groups')
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_attempts_user_tutorial')
        batch_op.drop_index('ix_practice_attempts_user_id')
        batch_op.drop_index('ix_practice_attempts_submitted_at')

    op.drop_table('practice_attempts')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_sessions_user_tutorial')
        batch_op.drop_index('ix_learning_sessions_user_id')
        batch_op.drop_index('ix_learning_sessions_started_at')

    op.drop_table('learning_sessions')
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index('ix_xp_events_user_id')
        batch_op.drop_index('ix_xp_events_source_type')
        batch_op.drop_index('ix_xp_events_created_at')

    op.drop_table('xp_events')
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_user_tokens_user_id')
        batch_op.drop_index('ix_user_tokens_user_active')
        batch_op.drop_index('ix_user_tokens_hash')

    op.drop_table('user_tokens')
    with op.batch_alter_table('user_login_streaks', schema=None) as batch_op:
        batch_op.drop_index('ix_user_login_streaks_user_id')
        batch_op.drop_index('ix_user_login_streaks_date')

    op.drop_table('user_login_streaks')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_user_identities_user_id')

    op.drop_table('user_identities')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_user_achievements_user_id')
        batch_op.drop_index('ix_user_achievements_unlocked_at')

    op.drop_table('user_achievements')
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_index('ix_tutorials_slug')
        batch_op.drop_index('ix_tutorials_published')
        batch_op.drop_index('ix_tutorials_category_order')
        batch_op.drop_index('ix_tutorials_category_id')
        batch_op.drop_index('ix_tutorials_category_graph')

    op.drop_table('tutorials')
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.drop_index('ix_explore_histories_user_id')
        batch_op.drop_index('ix_explore_histories_user_created')
        batch_op.drop_index('ix_explore_histories_detected_algorithm')

    op.drop_table('explore_histories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_table_record')
        batch_op.drop_index('ix_audit_logs_request_id')
        batch_op.drop_index('ix_audit_logs_event_timestamp')
        batch_op.drop_index('ix_audit_logs_event_id')

    op.drop_table('audit_logs')
    with op.batch_alter_table('algorithm_category_translations', schema=None) as batch_op:
        batch_op.drop_index('ix_algo_cat_trans_category_id')

    op.drop_table('algorithm_category_translations')
    with op.batch_alter_table('achievement_translations', schema=None) as batch_op:
        batch_op.drop_index('ix_achievement_translations_achievement_id')

    op.drop_table('achievement_translations')
    op.drop_table('users')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verifications_expires_at')
        batch_op.drop_index('ix_email_verifications_email_created')
        batch_op.drop_index('ix_email_verifications_email')

    op.drop_table('email_verifications')
    op.drop_table('algorithm_categories')
    with op.batch_alter_table('achievement_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_achievement_definitions_slug')
        batch_op.drop_index('ix_achievement_definitions_category')
        batch_op.drop_index('ix_achievement_definitions_active')

    op.drop_table('achievement_definitions')

    # XP Partial Unique Index
    op.execute("DROP INDEX IF EXISTS ux_xp_achievement")
    op.execute("DROP INDEX IF EXISTS ux_xp_practice_perfect")
    op.execute("DROP INDEX IF EXISTS ux_xp_practice_pass")
    op.execute("DROP INDEX IF EXISTS ux_xp_teaching")
    # ### end Alembic commands ###
