""""add_level1Flag_executionTrace_and_truncationStatus_to_explore_histories"

Revision ID: 5b0a14e3b608
Revises: b1c3e7f9a2d4
Create Date: 2026-04-06 01:32:55.094513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0a14e3b608'
down_revision = 'b1c3e7f9a2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('have_level1', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('execution_trace', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_truncated', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_xp_achievement'), postgresql_where="(source_type = 'achievement_unlock'::xpsourcetype)")
        batch_op.drop_index(batch_op.f('ux_xp_practice_pass'), postgresql_where="(source_type = 'practice_pass'::xpsourcetype)")
        batch_op.drop_index(batch_op.f('ux_xp_practice_perfect'), postgresql_where="(source_type = 'practice_perfect'::xpsourcetype)")
        batch_op.drop_index(batch_op.f('ux_xp_teaching'), postgresql_where="(source_type = 'teaching_complete'::xpsourcetype)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_xp_teaching'), ['user_id', 'source_id'], unique=True, postgresql_where="(source_type = 'teaching_complete'::xpsourcetype)")
        batch_op.create_index(batch_op.f('ux_xp_practice_perfect'), ['user_id', 'source_id'], unique=True, postgresql_where="(source_type = 'practice_perfect'::xpsourcetype)")
        batch_op.create_index(batch_op.f('ux_xp_practice_pass'), ['user_id', 'source_id'], unique=True, postgresql_where="(source_type = 'practice_pass'::xpsourcetype)")
        batch_op.create_index(batch_op.f('ux_xp_achievement'), ['user_id', 'source_id'], unique=True, postgresql_where="(source_type = 'achievement_unlock'::xpsourcetype)")

    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.drop_column('is_truncated')
        batch_op.drop_column('execution_trace')
        batch_op.drop_column('have_level1')

    # ### end Alembic commands ###
