"""add question_key and group_key

Revision ID: 780175a37a74
Revises: 21a559180677
Create Date: 2026-06-10 03:02:26.410077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780175a37a74'
down_revision = '21a559180677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_question_groups_key', ['tutorial_id', 'group_key'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_questions_key', ['tutorial_id', 'question_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_questions_key', type_='unique')
        batch_op.drop_column('question_key')

    with op.batch_alter_table('question_groups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_question_groups_key', type_='unique')
        batch_op.drop_column('group_key')

    # ### end Alembic commands ###
