"""add_algo_divergence_log

Revision ID: 8b2b80285f83
Revises: e965088926f9
Create Date: 2026-04-25 10:29:28.287920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2b80285f83'
down_revision = 'e965088926f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algo_divergence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('detected_algo', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_recursive', sa.Boolean(), nullable=False),
    sa.Column('expected_struct', sa.String(length=16), nullable=False),
    sa.Column('divergence_type', sa.String(length=32), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('algo_divergence_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_algo_divergence_logs_code_hash'), ['code_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_divergence_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_algo_divergence_logs_code_hash'))

    op.drop_table('algo_divergence_logs')
    # ### end Alembic commands ###
