""""fix_unify_last_seen_at_default_to_Python-side_for_AlgoDivergenceLog"

Revision ID: 929d103c7ec1
Revises: 8b2b80285f83
Create Date: 2026-05-09 07:26:39.565459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929d103c7ec1'
down_revision = '8b2b80285f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_divergence_logs', schema=None) as batch_op:
        batch_op.alter_column('expected_struct',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo_divergence_logs', schema=None) as batch_op:
        batch_op.alter_column('expected_struct',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
