""""drop_status_from_user_tutorial_progress"

Revision ID: aaaf99fb8bae
Revises: af4342c29fd9
Create Date: 2026-03-25 03:15:10.197556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaaf99fb8bae'
down_revision = 'af4342c29fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utp_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tutorial_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('teaching_in_progress', 'teaching_done', 'practicing', 'completed', name='tutorialstatus'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_utp_status'), ['status'], unique=False)

    # ### end Alembic commands ###
