""""add_base_rating_drop_points"

Revision ID: af4342c29fd9
Revises: 5dba896ebdd3
Create Date: 2026-03-25 02:19:53.066300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4342c29fd9'
down_revision = '5dba896ebdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_rating', sa.Float(), nullable=False, server_default='1200'))
        batch_op.drop_column('points')

    op.execute('UPDATE questions SET base_rating = difficulty_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('base_rating')

    # ### end Alembic commands ###
