"""add user_tokens table

Revision ID: cb82ef0058ea
Revises: 102313367aee
Create Date: 2026-03-05 04:17:00.912216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb82ef0058ea'
down_revision = '102313367aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('token_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_user_tokens_hash', ['token_hash'], unique=False)
        batch_op.create_index('ix_user_tokens_user_active', ['user_id', 'is_revoked', 'expires_at'], unique=False)
        batch_op.create_index('ix_user_tokens_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_user_tokens_user_id')
        batch_op.drop_index('ix_user_tokens_user_active')
        batch_op.drop_index('ix_user_tokens_hash')

    op.drop_table('user_tokens')
    # ### end Alembic commands ###
