""""add_llm_summary_to_explore_histories"

Revision ID: e965088926f9
Revises: 5b0a14e3b608
Create Date: 2026-04-09 01:52:31.726729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e965088926f9'
down_revision = '5b0a14e3b608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_histories', schema=None) as batch_op:
        batch_op.drop_column('llm_summary')

    # ### end Alembic commands ###
